{% set version = "0.6.2" %}

package:
  name: openapi-schema-validator
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/openapi-schema-validator/openapi_schema_validator-{{ version }}.tar.gz
  sha256: 11a95c9c9017912964e3e5f2545a5b11c3814880681fcacfb73b1759bb4f2804

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python
  run:
    - python
    - attrs >=19.2.0
    - jsonschema 
    - jsonschema-specifications
    - rfc3339-validator

test:
  imports:
    - openapi_schema_validator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/p1c2u/openapi-schema-validator
  summary: OpenAPI schema validation for Python
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
