{% set version = "0.3.0" %}

package:
  name: openapi-schema-validator
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/openapi-schema-validator/openapi-schema-validator-{{ version }}.tar.gz
  sha256: cf2c96a45c9a9722ea06fc7264d2fc55e0e6258ba8ef291d0ea90b4c5c8bdcfc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7
  run:
    - attrs >=19.2.0
    - jsonschema >=4.0.0,<5.0.0
    - python >=3.7

test:
  imports:
    - openapi_schema_validator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/p1c2u/openapi-schema-validator
  summary: OpenAPI schema validation for Python
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
