{% set name = "openapi-schema-validator" %}
{% set version = "0.1.6" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 230db361c71a5b08b25ec926797ac8b59a8f499bbd7316bd15b6cd0fc9aea5df

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - isodate
    - jsonschema >=3.0.0
    - python >=3.5
    - six

test:
  imports:
    - openapi_schema_validator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/p1c2u/openapi-schema-validator
  summary: OpenAPI schema validation for Python
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
