{% set version = "0.6.2" %}

package:
  name: openapi-schema-validator
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/openapi-schema-validator/openapi_schema_validator-{{ version }}.tar.gz
  sha256: 11a95c9c9017912964e3e5f2545a5b11c3814880681fcacfb73b1759bb4f2804

build:
  skip: true # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python
  run:
    - python
    - jsonschema >=4.19.1,<5.0.0a0
    - jsonschema-specifications >=2023.5.2,<2024.0.0
    - rfc3339-validator

test:
  source_files:
    - tests
  imports:
    - openapi_schema_validator
  commands:
    - pip check
    # skipping test_array_prefixitems_invalid because of https://github.com/python-openapi/openapi-schema-validator/issues/153
    - pytest -v -k "not test_array_prefixitems_invalid[value0]"
  requires:
    - pip
    - pytest

about:
  home: https://github.com/p1c2u/openapi-schema-validator
  summary: OpenAPI schema validation for Python
  description: |
    OpenAPI schema validation for Python
  doc_source_url: https://github.com/p1c2u/openapi-schema-validator
  dev_url: https://github.com/p1c2u/openapi-schema-validator
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  recipe-maintainers:
    - bollwyvl
