{% set name = "openapi-schema-validator" %}
{% set version = "0.6.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: f37bace4fc2a5d96692f4f8b31dc0f8d7400fd04f3a937798eaf880d425de6ee

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true # [py<38]

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python
  run:
    - python
    - jsonschema >=4.19.1,<5.0.0
    - jsonschema-specifications >=2023.5.2
    - rfc3339-validator

test:
  source_files:
    - tests
  imports:
    - openapi_schema_validator
  commands:
    - pip check
    - pytest -v 
  requires:
    - pip
    - pytest

about:
  home: https://github.com/p1c2u/openapi-schema-validator
  summary: OpenAPI schema validation for Python
  description: |
    OpenAPI schema validation for Python
  doc_url: https://openapi-schema-validator.readthedocs.io
  dev_url: https://github.com/p1c2u/openapi-schema-validator
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  recipe-maintainers:
    - bollwyvl
